INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '沃特篮球鞋', '佛山', 180, 500, '001.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '安踏运动鞋', '福州', 120, 800, '002.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '耐克运动鞋', '广州', 500, 1000, '003.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '阿迪达斯T血衫', '上海', 388, 600, '004.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '李宁文化衫', '广州', 180, 900, '005.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ('小米3', '北京', 1999, 3000, '006.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '小米2S', '北京', 1299, 1000, '007.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( 'thinkpad笔记本', '北京', 6999, 500, '008.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( 'dell笔记本', '北京', 3999, 500, '009.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( 'ipad5', '北京', 5999, 500, '010.jpg');
INSERT INTO db_mall.items ( name, city, price, number, picture) VALUES ( '张尧俊', '1', 1, 1, '999.jpg');